spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/courseWorkWeather_db
    username: postgres
    password: postdata
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect



